# GitHub Copilot configuration

# Enabled domains for firewall allowlist
allowed_domains:
  - index.crates.io
  - static.rust-lang.org
  - docs.rs
  - surrealdb.com

# Build instructions
build:
  command: cargo build

# Test instructions
test:
  command: cargo nextest run

# Use these environment variables during Copilot sessions
environment:
  RUSTFLAGS: "-C linker=clang -C link-arg=-fuse-ld=mold"
