name: GitHub Copilot Setuo Steps

on: workflow_dispatch

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    env:
      COPILOT_AGENT_FIREWALL_ALLOW_LIST_ADDITIONS: index.crates.io,static.rust-lang.org,docs.rs,surrealdb.com
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2025-05-14
          components: rustfmt, clippy

      - name: Install sccache
        uses: mozilla-actions/sccache-action@v0.0.4

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: "true"

      - name: Install mold linker
        run: |
          sudo apt-get update
          sudo apt-get install -y clang mold

      - name: Install cargo-nextest
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest

      - name: Setup build environment
        run: |
          echo "RUSTFLAGS=-C linker=clang -C link-arg=-fuse-ld=mold" >> $GITHUB_ENV

      - name: Build project
        run: cargo build
        continue-on-error: true

      - name: Run tests
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: cargo nextest run
        continue-on-error: true